name: "AI Translate"
description: "Translate text using AI"
author: "FidelusAleksander"
branding:
  icon: globe
  color: green
inputs:
  token:
    description: >
      Personal access token, can be passed as secrets.GITHUB_TOKEN
    default: ${{ github.token }}
  text:
    description: >
      Text to translate
    required: false
  text-file:
    description: >
      Path to a file containing the text to translate
    required: false
  target-language:
    description: >
      The language to translate the text into
    required: true
  model:
    description: >
      The AI model to use for translation
    default: "gpt-4o"
  custom-instructions:
    description: >
      Optional additional instructions to customize the translation behavior.
      For example: "Don't translate code blocks" or "Keep technical terms in English".
      Use this to control how specific parts of the text should be handled during translation.
    required: false
outputs:
  translated-text:
    description: >
      The translated text
runs:
  using: "node20"
  main: "dist/index.js"
